apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-direct-pv
spec:
  storageClassName: nfs-direct
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfsfileshare
    server: 192.168.33.14

